CREATE TABLE IF NOT EXISTS users (
                                     id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name  VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,

                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name        VARCHAR(255) NOT NULL,
                                     description TEXT NOT NULL,
                                     is_available BOOLEAN NOT NULL,
                                     owner_id    BIGINT NOT NULL,

                                     CONSTRAINT pk_item PRIMARY KEY (id),
                                     CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_items_owner_id ON items (owner_id);